services:
  nature-album:
    build:
      context: .
      args:
        - HTTP_PROXY=
        - HTTPS_PROXY=
        - http_proxy=
        - https_proxy=
    container_name: nature-album
    ports:
      - "8000:8000"
    environment:
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    volumes:
      - ./album:/app/album
      - ./thumbs:/app/thumbs
      - ./metadata_relic.json:/app/metadata_relic.json
      - ./metadata_animal.json:/app/metadata_animal.json
      - ./metadata_plant.json:/app/metadata_plant.json
    restart: unless-stopped
